services:
  - type: web
    name: wheech-website
    runtime: static
    repo: https://github.com/gils1908/Wheech-Website
    branch: main
    autoDeploy: true
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /privacy
        destination: /privacy.html
      - type: rewrite
        source: /terms
        destination: /terms.html
